### ISSUE TITLE
Youtube title not found

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#103]
Let's go here:

http://101companies.org/wiki/Selection_sort

The rendering of the video has a small issue:

![image](https://cloud.githubusercontent.com/assets/1208815/11214328/e516b3aa-8d40-11e5-84c6-03205e3e0967.png)

See "Title wasn't found".

**Comment by kevin-klein** [comment]
As it seems, youtube deprecated the used api and we would need a developer account and an api key to make this work.
A good alternative would be to use a third party side for now: http://noembed.com/
It would make a fix rather easy but i will need access to the wikicloth repo although i would suggest we migrate from @avaranovich repo to one repo owned by 101companies.
