### ISSUE TITLE
Pressing `New Tripe' clears the whole article if  the article does not contain `== Metadata =='

### ISSUE THREAD

**Issue by cEhlen** [101companies/101rails#107]
If you click on `New Triple' while editing a wiki page, the whole article gets replaced with the new metadata section.

The bug should be here:
https://github.com/101companies/101rails/blob/c4c0a98c12177595eae7ff49b3a9dea313b403a6/app/assets/javascripts/components/page_editor.js.jsx#L90

I will submit a pull request soon.

**Comment by kevin-klein** [comment]
Merged and deployed to production.
