### ISSUE TITLE
Contribution email contains broken link

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#109]
<pre>
---------- Forwarded message ----------
From: <101companies@gmail.com>
Date: Thu, Dec 10, 2015 at 1:01 AM
Subject: A new contribution 'OCL using USE' has been submitted
To: 101companies@gmail.com

A new contribution has been submitted. Please go here and verify the contribution.

101companies system.
</pre>

The broken link (around "here" above) is this:

https://github.com/cEhlen/cEhlen/OCL101Companies

**Comment by kevin-klein** [comment]
49819677f68ccc460f95e7acd3075eeec0e6eddc
