### ISSUE TITLE
How to see what contributions need admin approval and how to approve

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#110]
I just tried to do this for http://101companies.org/wiki/Contribution:OCL_using_USE
and http://101companies.org/wiki/Contribution:JML_Specs
I just knew that they may need approval.
When clicking around in the admin UI, I was not able to see where I could approve the contributions.
UI needs to be improved.

cc @cEhlen @AndrEm12 @dblM90 @felix-kloft

**Comment by dblM90** [comment]
The Contribution can be verified directly from the wiki. 
![Wiki](https://cloud.githubusercontent.com/assets/7570984/11931454/5d581cfc-a7ed-11e5-8b97-f2ac8978b1f4.PNG)
The verification in the admin ui is not done yet, because its an external plugin, but it should show the current status of verification in the pages tab...

**Comment by dblM90** [comment]
Oh, i made a mistake. The verification from within the admin ui is also possible by editing the page. There is a checkbox, where one can click the verified checkbox and save the change

**Comment by rlaemmel** [comment]
If I go to "Pages" in the admin UI
I only see an alphabetic list of pages and all pages seem to have the same marker in the "verified" column.
I tried to select a filter, but that doesn't work at all.
I do not see how to approve anything.
I guess Kevin and me should discuss.

**Comment by dblM90** [comment]
Yes, i've seen this to. All old pages are marked with a minus. But new pages, which are results of the contribution process, should marked with either a green hook or a red x. in development this works great, i dont know, if its not working in production only. 
also, if you verify an existing page, it should show a green hook, too.

**Comment by dblM90** [comment]
![Admin UI](https://cloud.githubusercontent.com/assets/7570984/11932211/e934e894-a7f3-11e5-87ec-714359815aaf.PNG)

**Comment by kevin-klein** [comment]
@rlaemmel and i discussed the "admin panel situation" and we agreed on changing the admin panel user interface, most likely this will be another gem but i tend to favor https://github.com/thoughtbot/administrate

**Comment by kevin-klein** [comment]
A first draft is online now: http://101companies.org/wiki/unverified It is accessible for admin users in the dropdown of the user name. Pages can also be unverified and a log is created for verifications.
