### ISSUE TITLE
Navigation from wiki to repo broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#112]
Let's start here:

![image](https://cloud.githubusercontent.com/assets/1208815/12574970/e9cd3ff0-c408-11e5-912e-2db2406dd5c1.png)

Now press "go to github".

We end up here:

https://github.com/cEhlen/cEhlen/OCL101Companies

... which means get a page not found.

It should be this URL:

https://github.com/cEhlen/OCL101Companies

**Comment by kevin-klein** [comment]
This was a temporary bug for a few days only which has been fixed already, i saved it again and it works for now. No other links seem broken.
