### ISSUE TITLE
contribute/new broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#117]
When pressing "Create contribution now"
![image](https://cloud.githubusercontent.com/assets/1208815/14178444/f4ac7af0-f75a-11e5-9eb9-7d6f9d90b48a.png)
... nothing really happens.

**Comment by kevin-klein** [comment]
It seems to be an issue related to wiki not being able to load some data from github. I am pretty busy right now but i will check into it tomorrow.
