### ISSUE TITLE
Page went missing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#121]
cc @MarcelH91 (who reported this).

http://101companies.org/wiki/List_comprehension used to be there.

I don't know when it went missing and let's assume it wasn't deleted on purpose.

**Comment by MarcelH91** [comment]
Further links, which have gone missing :
http://101companies.org/wiki/Algorithm
http://101companies.org/wiki/Algorithmic_problem
http://101companies.org/wiki/Search_problem
http://101companies.org/wiki/Search_algorithm
http://101companies.org/wiki/Linear_search
http://101companies.org/wiki/Binary_search
http://101companies.org/wiki/Sorting_problem
http://101companies.org/wiki/Sorting_algorithm
http://101companies.org/wiki/Quicksort
http://101companies.org/wiki/Selection_sort
http://101companies.org/wiki/Type_system
http://101companies.org/wiki/Type_signature
http://101companies.org/wiki/Polymorphism
http://101companies.org/wiki/Type_checking

Links from this page : http://101companies.org/wiki/Script:Searching_and_sorting_in_Haskell

**Comment by MarcelH91** [comment]
http://101companies.org/wiki/IO_monad

This page is missing as well.
