### ISSUE TITLE
Code not rendering

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#122]
http://101companies.org/wiki/Contribution:haskellMonoid

![image](https://cloud.githubusercontent.com/assets/1208815/15922689/673d9f9a-2e29-11e6-96aa-e587f8bca6e4.png)

**Comment by kevin-klein** [comment]
This is related to 101companies/101worker/issues/224

**Comment by MarcelH91** [comment]
Is it related to 101companies/101worker#224?
Since at http://101companies.org/wiki/Contribution:haskellMonoid and http://101companies.org/wiki/Stack the code is not rendered with the message : Retrieved empty json from discovery service.

**Comment by kevin-klein** [comment]
It was but 101companies/101worker#224 is definetly ok, i will see what is up here but is for sure unrelated.

**Comment by kevin-klein** [comment]
It seems like the haskell fact extraction did not work. I will fix this asap.
