### ISSUE TITLE
101Explorer link broken

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#123]
The button named "explore now" at http://101companies.org/#explorer. Does not work right now.

Error message : 404 Not Found

**Comment by kevin-klein** [comment]
We decided to retire the current version of the explorer, what do you
expect me to do? I would remove the link

**Comment by rlaemmel** [comment]
@kevin-klein Kevin - how should we go about this?
Should we may be not show "Explore now"?
As the service will not work for a while.
When Andi's work will be completed, it could be activated again.
The tab for 101explorer on the wiki page should be also disabled.

**Comment by rlaemmel** [comment]
Oops.
We concurrently replied :-)
But I guess we are in agreement.

**Comment by kevin-klein** [comment]
I disabled the link for now.
