### ISSUE TITLE
Pages lacking namespace prefix

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#125]
That's an old omnipresent issue.

For instance, go here:

http://101companies.org/wiki/Bidirectional_transformation

haskellTree is a contribution, but it also gets listed without namespace:

![image](https://cloud.githubusercontent.com/assets/1208815/16100337/05999c82-335e-11e6-9eb0-9b3c8a46e05f.png)

**Comment by kevin-klein** [comment]
duplicate if #143
