### ISSUE TITLE
101repo tab can be misleading

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#127]
Consider this context, for example:

![image](https://cloud.githubusercontent.com/assets/1208815/16519713/3efc6002-3f8b-11e6-8882-b4aaac1a2ba9.png)

Someone may expect to go the 101repo.
I think 101repo should only be shown if the particular page was represented in the 101repo.
Otherwhise, one should be taken to the dialog for entering a folder and the page should clearly link to 
http://101companies.org/wiki/101repo

**Comment by rlaemmel** [comment]
Here is just what I replied to a person with a related inquiry:

The "101repo" tab is on *every* page of the wiki and would take you to a repo location, *if* that particular page has designated content in the repo. Typically, only contribution pages have a repo location.

For instance, this one has:

http://101companies.org/wiki/Contribution:pyjson

If you want to access the repo as a whole, you might prefer doing this through github -- only the challenge is that the contributions are distributed over many physical repos. These are some important ones:

https://github.com/101companies/101repo
https://github.com/101companies/101simplejava
https://github.com/101companies/101haskell

We shall reenable a convenient zip download for all contributions.

**Comment by rlaemmel** [comment]
In fact, the zip with all code appears to be this:

http://data.101companies.org/zips/101repo.zip

I am going to link this URL on the wiki/101repo page.

The rest of the "issue" remains valid.

**Comment by kevin-klein** [comment]
i changed it so that it only shows 101repo if it exists or the user is logged in and can change the link, is that what you wanted?

**Comment by MarcelH91** [comment]
Are you sure that it works properly? There is no 101Repo button for http://101companies.org/wiki/Contribution:hughesPJ for example, even though I think that it should be there.

**Comment by MarcelH91** [comment]
I see. Yes, that is better. Even though I even oversaw it at first, since I expected to see a `101Repo' button. I don't know whether someone would find it, who doesn't know the Wiki. I'll let some students look at it.

**Comment by MarcelH91** [comment]
Okay, so I let someone else look at it. I asked a student to find the link to a contributions source code somewhere at the contribution page. The first button that she clicked on was `Show source', which I guess could be the most obvious choice for outsiders. I could ask others to do the same, though I think that the outcome would be the same.

Let me make some proposals again:
- Rename 'Show source' to 'Edit'. 
- Rename 'Go to Github' to 'Show code' (Or rename it to something else that is more direct. I don't know what would be best here.) This text should be bold as well.
