### ISSUE TITLE
Contribution to Repo Link

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#129]
Hi,

in the FP lab people were surprised by the fact that there is a link from a contribution to a github repo, where you can find even more code. All softlang team members know that there is always this kind of link from a contribution to a github repo, but the question is whether outsiders can see this fact or are provided with some guidance.

The only guide on what the whole wiki is all about seems to be at http://101companies.org/wiki/101project. At any wiki page we should provide some help/guidance on what this is and not just on what it describes. The namespaces might not always help outsiders.

Actually, I wonder how many people click on "help" to find exactly this information and get a list of possible markups for editing wiki pages instead. At least this happened to me. I just noticed why : At wikipedia it is realized this way. For example, if you click on "Help" at a category page like https://en.wikipedia.org/wiki/Category:Computer_languages this page opens: https://www.mediawiki.org/wiki/Help:Categories that explains what categories are for and other details. 

Best Regards,
Marcel

**Comment by rlaemmel** [comment]
cc @MarcelH91 
cc  @kevin-klein 

I completely agree that this is a usability issue and needs to be addressed.
We are loosing people here for a relatively reason.
@kevin-klein let's discuss and maybe you can tune the UI a bit.
There is also other pending UI stuff.

Thanks,
Ralf

**Comment by MarcelH91** [comment]
The issue was discussed and is dealt with in more concrete issues such as https://github.com/101companies/101rails/issues/132
