### ISSUE TITLE
Help/101Wiki views buggy

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#131]
Hi,

the following bug is apparent at any Wikipage such as http://101companies.org/wiki/Fold_function.
You click on `Help', which opens Syntax for editing wiki. Then, you click on `101wiki' and the `Syntax for editing wiki' remains in place instead of switching to the wiki content.

![neue bitmap](https://cloud.githubusercontent.com/assets/8490924/17328068/d508ed2e-58bb-11e6-9585-f521669f3bcb.jpg)

**Comment by kevin-klein** [comment]
57dcc6673a9d4c8d16e516db585b172543a09c21
