### ISSUE TITLE
Improve visibility of 101Repo link

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#133]
I asked a student to find the link to a contributions source code somewhere at a contribution page. The first button that she clicked on was `Show source', which I guess could be the most obvious choice for outsiders. I could ask others to do the same, though I think that the outcome would be the same. We have to make it easier for people to find this link.

Let me make some proposals again:
- Rename 'Show source' to 'Edit'.
- Rename 'Go to Github' to 'Show code' (Or rename it to something else that is more direct. I don't know what would be best here.) This text should be bold as well.

**Comment by kevin-klein** [comment]
I agree with your proposal, it is change in the live version.
