### ISSUE TITLE
Some fine tuning for the "render script" button

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#134]
It looks like this at the moment:

![image](https://cloud.githubusercontent.com/assets/1208815/17438698/880d3028-5b24-11e6-805e-9d74efdea5f0.png)

I suggest to replace "render script" by "Save As" and move the button to the right end of the list of buttons.

Also, I suggest to not directly start the process, but to bring up a modal dialog:

Title: Save Page As HTML
Text: Do you really want to save the current page and all referenced pages?
The result will be stored here:
http://data.101companies.org/pages
Buttons: Ok and Cancel

Let's use http://data.101companies.org/pages
and not http://data.101companies.org/scripts

**Comment by kevin-klein** [comment]
c32980b0515595611ea6fd9e884346781306be37
