### ISSUE TITLE
Separator line in saved HTML

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#135]
Looking at http://data.101companies.org/scripts/Course%3aLambdas%20at%20UvA.html

Here is how the separation between pages looks like:

![image](https://cloud.githubusercontent.com/assets/1208815/17438951/d963af64-5b25-11e6-9148-9942a898e136.png)

I suggest to use a much more visible separator line so that it becomes more easy to notice when one transitions between pages.

**Comment by kevin-klein** [comment]
it was just a deployment issue, please regenerate the concerning pages and it will have a bold black line at the bottom of every page.
