### ISSUE TITLE
Style of metadata in saved pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#136]
I am looking at this: 

http://data.101companies.org/scripts/Course%3aLambdas%20at%20UvA.html

The metadata looks like this:

![image](https://cloud.githubusercontent.com/assets/1208815/17439004/1e1faf40-5b26-11e6-8a73-f3e81a4f9618.png)

The chosen colors make it hard to actually see the links.

**Comment by kevin-klein** [comment]
c32980b0515595611ea6fd9e884346781306be37
