### ISSUE TITLE
Copyright in saved pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#138]
At the beginning of each page (also at the beginning of the first page!) and possibly "as part" of the separator line some copyright notice is needed. I was thinking of this:

(C) 2012--2016 101companies.org and softlang.org

This should be centered.
The fond should be smaller than the regular font.
The domains should be linked.
"2016" should be computed to be the current year.

**Comment by kevin-klein** [comment]
is it ok this way? http://data.101companies.org/pages/Course%3aLambdas%20at%20UvA.html

**Comment by rlaemmel** [comment]
yes, great, except that we also want it at the top, i.e., for the first page.

**Comment by rlaemmel** [comment]
I just realize that "(C) 2012--2016 101companies.org and softlang.org" was added also on the regular view of pages on the wiki.

It shows up at the bottom. Maybe, this is actually the right thing to do. Then, it also makes sense to only see the copyright as part of the separator lines and not the top.

So I am ready close the issue.
