### ISSUE TITLE
Button renaming

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#139]
I am logged off and see this:

![image](https://cloud.githubusercontent.com/assets/1208815/17456590/503a0f9a-5bdd-11e6-82d4-df15dbed1b25.png)

Arguably, "Edit" is misleading; if I try to edit then the save button is also shown, but not working. 

So maybe renaming of "Edit" to "Markup" (or "Show Markup", but short is cool) would make sense. Also, "Save" and "Cancel" buttons  should then be replaced by just "Close" button.

Further, "Show source on GitHub" is too long.
Would "GitHub" just be enough?

**Comment by kevin-klein** [comment]
i changed it to github, is deployed as well

**Comment by MarcelH91** [comment]
Why is there a 'Show markup' button for non-editors in the first place?

On 'Github' button : We should make an experiment, because I don't think that first semester students will get what this button does, since they don't know Github.

**Comment by rlaemmel** [comment]
Show Markup is there so that people can start experience Markup without being logged in.
Arguably, it is not needed indeed. 
Wiki systems tend to have something like this.
As to the GitHub button, yes, you are right maybe the GitHub mentioning is sort of wired. 
I cannot think of anything short though that is completely clear to everyone.
So we need a 101 cheat page which mentions the role of GitHub :-)

**Comment by rlaemmel** [comment]
I think it is good for now.
