### ISSUE TITLE
Escaping or pre formatting in running text of wiki

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#142]
Suppose I want to show some code within the regular text on a wiki page, I am not aware of any options. Both the syntaxhighlighting and the pre markup elements cause linebreaks and are thus not fit for inlining.

However, it occasionally is really important to do it.

For instance, how can I talk about the empty list "[]"? I cannot.

I don't know what to do. One option is to handle the "pre" tag in the running text in a special manner. The other probably more robust option is to add escaping.

**Comment by kevin-klein** [comment]
just use  `<code>Text</code>`. Example:http://101companies.org/wiki/Contribution:pythonSyb (red gmaT and gmapQ).

**Comment by rlaemmel** [comment]
Maybe, this works.
Within the editor, when choosing "code", you get the "syntaxhighlight" template.
So we need unambiguous support in the editor.
