### ISSUE TITLE
search returns a lot of doubles and presumably irrelevant stuff

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#143]
Try this:

http://101companies.org/search?q=binary+search

Just showing some part of the search results

![image](https://cloud.githubusercontent.com/assets/1208815/17695188/b6ff237e-63a7-11e6-8e8e-c4e1a64ef368.png)

**Comment by kevin-klein** [comment]
there was an issue in the code deleting doubles, doubles are gone pretty sure, but there is this issue with concept pages like here: http://101companies.org/search?q=haskell i considered deleting concept pages when there is a contribution page with the same name but i could think of cases where i would remove valid pages, what is your proposal to do?

**Comment by rlaemmel** [comment]
I am just concerned that pages show up multiple times (and sometimes MANY times).

For instance, when clicking your URL http://101companies.org/search?q=haskell, I get this:

![image](https://cloud.githubusercontent.com/assets/1208815/17718843/9f8ee930-6416-11e6-8049-392640486fdf.png)
