### ISSUE TITLE
editing broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#149]
Tried to edit the following page.
Upon save and also upon load I get this:

![image](https://cloud.githubusercontent.com/assets/1208815/19777346/1b9a168c-9c78-11e6-9e4e-b50aca9041a7.png)

I also tried editing another page; it is also broken.

http://101companies.org/wiki/Technology:Haxe

**Comment by kevin-klein** [comment]
62fdcff2eb8ec3d5246ecf87ad0e62a324df4915
