### ISSUE TITLE
Turbolinks do not work with a dot in the url

### ISSUE THREAD

**Issue by myaicloud** [101companies/101rails#151]
The turbolinks generally work in 101linkeddata but on changing to a page with a dot ( . ) in the url e.g. ".../resource/language-vb.net". A click on a link like that causes a regular redirect.

I tried to check this issue in the 101wiki but there you can't open a wikipage with a dot in the url.
"http://101companies.org/wiki/Language:VB.NET" is navigating to the 101wiki landing page (http://101companies.org/wiki/101project). But that could be another issue.

**Comment by myaicloud** [comment]
Notice my expression for the "resource/" subdirectory in routes.rb

**Comment by kevin-klein** [comment]
It was actually a problem unrelated to turbolinks, urls containg a "." where not valid.
