### ISSUE TITLE
Quality Assurance for Articles

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#153]
I just searched for 'Code generation' in our Wiki and actually found two articles, where one seems to be in the namespace Concept and the other in the namespace Feature. At least that is what the search results suggest. Both have the very same content. Seems like Copy & Paste.

http://101companies.org/wiki/Code_generation
http://101companies.org/wiki/Feature:Code_generator

Two questions came in my mind:
Do we have any kind of mechanisms for quality assurance of articles?
Do we keep track of which articles still need more work?

**Comment by kevin-klein** [comment]
i think it might be a relic, there may have been a Feature:code_generation which was duplicated due to technical issues and was later renamed to code generator, so the concept:code_generation would have been left over.
