### ISSUE TITLE
Tooltip 'Script'

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#154]
Hi,

I just saw that the new feature 'Script' is now available. It took me a minute until I remembered that this is probably the button to generate a lecture script. Maybe it makes sense to add a tooltip. Otherwise, I guess that students won't know that it exists even though the button is there.

Best regards,
Marcel

**Comment by kevin-klein** [comment]
Any proposals on what that should be?

**Comment by MarcelH91** [comment]
"Generate a lecture script"
would probably be enough? I can test this later or tomorrow with some students that come to my office.
