### ISSUE TITLE
Inbound metadata missing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#164]
I am here:

https://101companies.org/Design_pattern

The Metadata section does not show "instanceOf" triples for all the actual patterns.
(The patterns are shown in the backlink section.)

For instance, see this:
https://101companies.org/Singleton_pattern
It does say "instanceOf Design_patterm".
So it should be also listed in the metadata section of Design_pattern.
(It used to be that way.)

**Comment by kevin-klein** [comment]
@avaranovich transfered it to me for some reason, @softlang should have a request.
