### ISSUE TITLE
101wiki.softlang.org needs to be primary domain

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#167]
cc @sschauss

Thus:
* 101companies.org/... should be redirected there.
* 101companies.org/wiki/... should be redirected there.
* Most importantly, login should be feasible on 101wiki.softlang.org

**Comment by kevin-klein** [comment]
login works, i am looking into the redirect stuff.

**Comment by kevin-klein** [comment]
should all be done now.
