### ISSUE TITLE
Improve UI for hitting a non-existing page.

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#168]
![image](https://cloud.githubusercontent.com/assets/1208815/25568728/8259eb86-2e09-11e7-8386-dd8acc28107f.png)

This looks odd that one has to read a text.
Can this be a more standardized dialogue?

**Comment by kevin-klein** [comment]
what do you mean by "standardized dialog"?

**Comment by rlaemmel** [comment]
Something like a button or several buttons with some brief question.
Maybe something comparable to what happens when deleting a page.
