### ISSUE TITLE
<pre> ... </pre> not working in some case

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#172]
I am here:
https://101companies.org/Metadata

I am seeing:
![image](https://cloud.githubusercontent.com/assets/1208815/25583038/5f0f7556-2e90-11e7-961c-aef38f91e9f1.png)

That is, the content of the illustration is not rendered.
The content happens to be wiki markup.
Not sure whether this is relevant.

**Comment by kevin-klein** [comment]
what do you mean by "the content of the illustration" is not rendered? i think it is below this :ghost: ```<pre></pre>```. i think the issue is unrelated to your ```pre``` usage, as this issue still occurs even if you did not use ```pre``` on this page. probably a problem in the wiki parser library.

**Comment by rlaemmel** [comment]
Ok, I was confused by the empty box that is shown in my OP.
I see that the content is actually shown in a separate box (in a place where it belongs).
What should we do here about the empty box?
File a new issue?

**Comment by kevin-klein** [comment]
no, i think i got this. just a little more complex to figure out as the library is rather complex.

**Comment by kevin-klein** [comment]
It appears, that there was a tab in the line after the ```== Illustration ==``` which seems to be the expected behavior for wiki markup. if this occurs more often, i can remove empty ```<pre>```.
