### ISSUE TITLE
Refined options for search

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#177]
When searching and NOT clicking "Title only" titles should still be searched
That's at least the semantics of "Not title only" I would expect.
Perhaps, there should be two checkboxes:

* Search titles
* Search content

Both should be checked by default.

**Comment by kevin-klein** [comment]
it searches in both title and content if you dont click it. i will add the other checkboxes.

**Comment by rlaemmel** [comment]
No, it really doesn't -- at least not for properties.
Try searching a property: you will find only references, but not the declaring page.

**Comment by kevin-klein** [comment]
we save namespace and title seperatly, you mean it should also search in the namespace?

**Comment by rlaemmel** [comment]
Let's run this search:
https://101wiki.softlang.org/search?namespace%5Bname%5D=Property&q=facilitates
We should see this:
https://101wiki.softlang.org/Property:facilitates

**Comment by kevin-klein** [comment]
this is actually a special case. if you search for a property namespace thing it only looks at the triples but i can make it look for titles as well.

**Comment by kevin-klein** [comment]
for other namespaces it does what you expect it should do

**Comment by rlaemmel** [comment]
https://101wiki.softlang.org/search?namespace%5Bname%5D=Property&q=facilitates
This is without checked "Title only".
So this reads like "not title only" = "title included and everything else".
But Property:facilitates is not listed.
So I think my originalp proposal makes sense.

**Comment by kevin-klein** [comment]
should work now
