### ISSUE TITLE
Weird namespaces

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#183]
I just noticed this kind of namespaces: See Dotnet and Java.

https://101wiki.softlang.org/Dotnet:System.Xml
https://101wiki.softlang.org/Java:javax.swing

Do we still want this? Or would we rather remove the namespaces? 
I think that we need to be consistent when using namespaces. For now, it seems as if we'd rather use them to refer to any entity's root type, such as Technology.  :-)

**Comment by kevin-klein** [comment]
this has been an ongoing discussion about this stuff for a very long time, @rlaemmel needs to make a decision how we handle this

**Comment by MarcelH91** [comment]
Since Ralf wants to align things here further with MegaL, I'd propose to remove this namespace and add technology spaces as a new namespace. 

OR:
You don't add the space since this space can be retrieved by a query that, for example, asks for everything that uses Java.

Anyways, in my opinion javax.swing should have the namespace Technology. It's easier to be consistent.

**Comment by rlaemmel** [comment]
I cannot make my mind on this yet.
Let's keep this open until we have improved content quality in more obvious ways.
