### ISSUE TITLE
Cannot cancel creating new page

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#185]
I went here:
https://101wiki.softlang.org/Technology:SWT/

Which sent me here:
https://101wiki.softlang.org/Technology:SWT/create_new_page_confirmation

I clicked cancel and the dialog that asks you whether you want to create a page pops up again.

![grafik](https://cloud.githubusercontent.com/assets/8490924/26355263/480613bc-3fc8-11e7-8dea-723ffc316065.png)

**Comment by MarcelH91** [comment]
Let me clarify something: As soon as I click on 'Cancel' it sends me here:
https://101wiki.softlang.org/Static%20annotation/create_new_page_confirmation#
So it adds the '#' and then the dialog appears again asking the same thing.

**Comment by kevin-klein** [comment]
just for clarification, the expected behavior is to go back when you click cancel, in this case there is no back, so the browser did nothing, now it redirects to /101project.
