### ISSUE TITLE
Buttons in Toolbar disappear when writing long lines of text.

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#186]
I was just editing the content of this:
https://101wiki.softlang.org/Structured%20Editor/

As soon as you write text in one line that goes beyond the right border this happens:

![grafik](https://cloud.githubusercontent.com/assets/8490924/26357448/8e812f28-3fcf-11e7-93be-9d4a0c87326a.png)

As you can see, a part of the upper toolbar disappears including the page's title.

**Comment by kevin-klein** [comment]
For me it looks like this:
![fireshot capture 1 - - https___101wiki softlang org_structured 20editor_edit](https://cloud.githubusercontent.com/assets/3279763/26358175/feffaf98-3fd1-11e7-8641-c25679cee539.png)


It might be a screen resolution problem, what resolution do you use?

**Comment by MarcelH91** [comment]
3440 x 1440
Though I have firefox only at the left half of my screen, so it is reduced to sth. like 1720 x 1440.
