### ISSUE TITLE
Bug: Broken GitHub links in (my) contributions

### ISSUE THREAD

**Issue by fruether** [101companies/101rails#196]
There is a bug in the contribution process provided by the [101wiki](https://101wiki.softlang.org/contribute/new). If a new contribution was created the GitHub links are broken. For example take the following contributions provided by me:

- https://101wiki.softlang.org/Contribution:101spark
- https://101wiki.softlang.org/Contribution:101kafka

If you are clicking on the GitHub repo of the contribution:

<img width="358" alt="bildschirmfoto 2017-06-04 um 12 27 02" src="https://cloud.githubusercontent.com/assets/1591040/26760758/2e2912ca-4921-11e7-8bbc-808b5451837b.png">

you are lead to a broken page: 
<img width="981" alt="bildschirmfoto 2017-06-04 um 12 27 58" src="https://cloud.githubusercontent.com/assets/1591040/26760762/46e6c12c-4921-11e7-866c-c3183d0a691f.png">

The reason for this is that the username is twice in the URL: https://github.com/username/username/101contribution

The actual URL should be: https://github.com/username/101contribution

Or to make it concrete: 
**How it should be**: https://github.com/fruether/101kafka
**How it is currently:** https://github.com/fruether/fruether/101kafka

The user has no possibility to select or adapt the URL since the UI is doing creation of the URL. The only thing the enduser is doing is to select the repo. Therefore, it seems like it is  a bug inside the system.
<img width="908" alt="bildschirmfoto 2017-06-04 um 12 32 50" src="https://cloud.githubusercontent.com/assets/1591040/26760801/f2f264f8-4921-11e7-9383-a66c7e8b3b27.png">

**Comment by MarcelH91** [comment]
https://101wiki.softlang.org/Contribution:mongodb

Linking to other repos seems to work here, but this is a very old contribution.
