### ISSUE TITLE
Renaming broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#200]
Trying to rename some contribution pages (javaMessaging...).
In one case, it succeeded eventually after trying like 5 times.
In another case, still trying.

**Comment by rlaemmel** [comment]
Succeeded now.
Seems to be some timing issue.

**Comment by kevin-klein** [comment]
feeeb145689937c85abe6ed45cbe48492fe83010
this might fix the timeout issue, depending on the page you rename, it runs number of refering pages + referenced triples sql queries so if you rename a very often referenced page, it will take longer, i tested the most referenced pages and for it takes no longer than 5 seconds, so it should be fine now. if this issue persist i can change this to work in a background processing manner but i would like to avoid it for now if it works like this.

**Comment by rlaemmel** [comment]
I was just trying to rename some properties and thus, I noticed some pattern. 
That is, the first renaming attempt doesn't seem to have any effect.
If quick enough attempted, the second attempt would even remember the entered value and then go through.

**Comment by rlaemmel** [comment]
I don't think it is a *timeout* issue. Pretty much always *nothing* happens when trying to rename.

**Comment by rlaemmel** [comment]
BTW, typo in message: "Page Perspective:Capture was rename to Perspective:Capture".
Should be "renamed".
Also, as it reads like a sentence, it should have a final ".".

**Comment by kevin-klein** [comment]
i tested everyting i can imagine and i can be a little sluggish, lets maybe talk tomorrow. i think there is some misunderstanding here. but i fixed the typos.

**Comment by rlaemmel** [comment]
I see very reliable non-working behavior :-)
Just tried to rename this:
https://101wiki.softlang.org/System:101
Dialogue finishes fine; one stays on that side; reload clarifies that no renaming has happened.
Tried one more time; again nothing happens.
Tried one more time (this time without reload); now the dialogue remembers my preferred name and when I just enter the renaming also happens.

**Comment by rlaemmel** [comment]
And btw, the message now reads like "Page System:Company was renamed to System:Company.".
Maybe this explains part of the problem.
(Because the page was called System:101.)

Anyways, this sort of behavior I get with any renaming in recent days.

**Comment by rlaemmel** [comment]
It looks like renaming is broken in some other way.
Here is an indication that renaming System:101 to System:Company was not completed fully.

![image](https://user-images.githubusercontent.com/1208815/27582777-78d4353e-5b32-11e7-8906-45d88a12471d.png)

**Comment by rlaemmel** [comment]
And it looks like search is co-broken.
Even though exemplifiedBy System:101 is there, search does not find it; see below.
In fact, search reports one occurrence of System:101, but inspection shows that there is no occurrence; see also below.

![image](https://user-images.githubusercontent.com/1208815/27582862-c5934b44-5b32-11e7-8500-84258b3ae7bf.png)

**Comment by kevin-klein** [comment]
the correct search would be System:101. selecting a namespace limits the scope of the search.

**Comment by rlaemmel** [comment]
What search URL do you mean and why is the above search result sensible?
