### ISSUE TITLE
Rendering of "unknown" file types

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#203]
I am here:

https://101wiki.softlang.org/Contribution:haskellEngineer

![image](https://user-images.githubusercontent.com/1208815/27518122-a20e5f0c-59d8-11e7-93cd-068928da7527.png)

There are two problems:

* The content of the file is shown without linebreaks (see here https://github.com/101companies/101haskell/blob/master/contributions/haskellEngineer/haskellEngineer.cabal for comparison). I think this means that files of "unknown" file types are just shown like this, but I think being faithful to linebreaks should be the default.
* The URL of the file is not discoverable (clickable) in the view.

**Comment by kevin-klein** [comment]
d917e3eae083fb99c7d5b1f22763f014ae53e715
