### ISSUE TITLE
Search misses something

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#215]
I added "[[similarTo::Section:FooBar]]" to a page.
Then I tried to search Section:FooBar.
I would not find the page.
If I do the same without any prefix (here: 'Section'), then search succeeds.

**Comment by kevin-klein** [comment]
seems to work for me, might have been fixed by something unrelated

**Comment by rlaemmel** [comment]
Search:
https://101wiki.softlang.org/search?namespace%5Bname%5D=System&q=101
Result:
https://101wiki.softlang.org/System:Company

However, System:101 cannot be found (and should not be) in the content.

**Comment by kevin-klein** [comment]
yes, but it only looks at pages in the system namespace and does a fulltext search for 101 which System:Company does contain, i admit the semantics are a little hard to predict. i think we should have someting more predictable.

**Comment by kevin-klein** [comment]
i pushed a new search system, i think this approach might be more intuitive, if you want to search for:

- all occurences of a property: https://101wiki.softlang.org/search?q=Property%3AexemplifiedBy
- text within a namespace: https://101wiki.softlang.org/search?q=Java+inNamespace%3Dconcept

i will have ranking and more advanced features soon, we should probably set up an internal page with some description on this.

**Comment by rlaemmel** [comment]
It looks like the UI doesn't support namespace search anymore.
