### ISSUE TITLE
Edit Note missing on some pages

### ISSUE THREAD

**Issue by mmonschau** [101companies/101rails#219]
e.g.
https://101wiki.softlang.org/Contribution:mongodb 
is missing
XY edited this article at ??????

and 

https://101wiki.softlang.org/Language:Scala
has that label at the bottom.

Don't know whether this is an "intended" migration "feature" or an actual bug.

this seems only to affect pages which were not edited recently.

**Comment by kevin-klein** [comment]
the page revision feature was broken for some time and was fixed when i
migrated to postgres so the revisions are missing for page edits which are
older than ~1 year.

2017-07-25 14:44 GMT+02:00 Michael Monschau <notifications@github.com>:
