### ISSUE TITLE
"New Triple" in edit mode not working

### ISSUE THREAD

**Issue by mminski** [101companies/101rails#221]
Seems like its an JS issue in file https://github.com/101companies/101rails/blob/master/app/assets/javascripts/components/page_editor.js.jsx

The variable new_predicates is out of scope for the function onChangeTriples.

![screenshot from 2017-08-15 11-31-20](https://user-images.githubusercontent.com/4227987/29310761-5f905ec4-81af-11e7-861c-3c5b76e04b55.png)

**Comment by MarcelH91** [comment]
It isn't working for me as well. I just added the '*' character in front of the triples.
