### ISSUE TITLE
Error Message bug for Technology

### ISSUE THREAD

**Issue by MarcelH91** [101companies/101rails#224]
See https://101wiki.softlang.org/Technology:org.apache.tools.ant

Message: "Invalid domain for uses::Language:Java, 'uses' has domain Contribution"

But the page is about a technology. Thus, it is actually not in the namespace contribution.

**Comment by kevin-klein** [comment]
Maybe i got the idea of the validation wrong but does hasDomain:Contribution not mean that only contribution pages can use this property?

**Comment by MarcelH91** [comment]
Ah, sorry, the error message mislead me here. You're right.
