### ISSUE TITLE
wiki looses prefix and creates multiple copies of pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#62]
Consider this:

http://101companies.org/wiki/Course:Lambdas_in_Koblenz

![image](https://cloud.githubusercontent.com/assets/1208815/7285550/b0871de0-e945-11e4-8210-21c476e8a9d5.png)

See the red stuff.

So I ran a search:

![image](https://cloud.githubusercontent.com/assets/1208815/7285565/bf6b112c-e945-11e4-86a2-0ee15758886b.png)

All the three pages ending on "... engineering in Haskell" seem to be copies.

It could be that these pages were created at some point by a broken "rename" feature.

Anyway, I wiped out some those not wanted and renamed some more so that the link should work.

It remains RED as shown above, despite being correctly resolved when clicked.

Same for the "... data modeling" link.

My hypothesis:

- "Rename" may have problems, but I can't reproduce this right now.
- RED coloring for links is definitely broken.

At least the resolvable links should not be shown in RED.

**Comment by kevin-klein** [comment]
So i should fix the red coloring?

**Comment by rlaemmel** [comment]
Yes, if you can produce the red link and if the link also works for you, then please see why it is red and how to avoid such issues.

Thanks!

**Comment by kevin-klein** [comment]
we agreed to remove red links so this is done
