### ISSUE TITLE
Double entries in search

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#63]
As one can, see various contributions are listed with the "Contribution" prefix and also without.

I checked some and it looks like the page without prefix does not exist.

See recent issue #62 where both pages (with a different prefix, though) did exist.

In any case, the search results should not show non-existing pages.

Clearly, there is something going on with loosing prefix as of #62.

![image](https://cloud.githubusercontent.com/assets/1208815/7294761/805c1222-e9b0-11e4-8fe0-42c7dbddbcdb.png)

**Comment by kevin-klein** [comment]
I removed the double entries.
