### ISSUE TITLE
101wiki contribution process

### ISSUE THREAD

**Issue by martinleinberger** [101companies/101rails#67]
# Summary

One of the biggest problems of the 101companies project is that submitting a new contribution is basically impossible, even though the basic idea is quite simple. 

A good submission process would start with a developer expressing the wish to submit a new contribution through the 101wiki web interface. He would then be able to provide a Github link. 101wiki notifies [101worker](https://github.com/101companies/101worker) of the additional contribution. 101worker downloads and analyzes it and can provide metadata such as the languages used in the contribution. 101wiki takes this information and provides a wiki page to the developer including the information computed by 101worker in which the developer documents and explains his contributions. After saving the page, the 101wiki admins get notified via email, review the contribution and make it publicly available. 

# Necessary features
* Page for submitting new contributions
* Being able to specify a Github link to a contribution
* 101wiki notifying 101worker of the new link [**broken/unimplemented**]
* 101wiki noticing 101worker has finished analyzing the new submission [**broken/unimplemented**]
* 101wiki being able to access the metadata provided by 101worker [**broken/unimplemented**]
* 101wiki taking the developer to a page where he can document his contribution using/reviewing the data provided by 101worker [**broken/unimplemented**]
* 101wiki notifying the admins of the new contribution [**broken/unimplemented**]

**Comment by kevin-klein** [comment]
I suppose this is fixed.
