### ISSUE TITLE
intellisense for adding a link

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#75]
This would be cool.
Say when selecting the "link" feature from the editor help ...

![image](https://cloud.githubusercontent.com/assets/1208815/7729928/a4f6cb28-ff17-11e4-8eed-434cbaacdf3f.png)

... if we were provided with real-time intellisense for selecting prefixes and then selecting members within the namespace.

For this to work smoothly for anyone who is creating a bunch of pages about the same time (hour), we would need more frequent worker cycles. https://github.com/101companies/101worker/issues/196

**Comment by kevin-klein** [comment]
There is support for auto complete of namespace members, the rest will follow.
