### ISSUE TITLE
a bit of space before each new section

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#76]
Consider this:

![image](https://cloud.githubusercontent.com/assets/1208815/7730801/a2fb1086-ff1c-11e4-9c10-c13a5f1a45ff.png)

The section headers "Metadata" and "Backlinks" (and generally all such headers) are very close to the previous section. There should be some tiny gap so that one can see that a new section starts. ("It used to be like this.")

**Comment by kevin-klein** [comment]
b55eae061d9097280d197adb79d1e88e653a2c16
