### ISSUE TITLE
file urls on the wiki end up on empty 101explorer page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#78]
cc @martinleinberger 

An example from today's lecture:

http://101companies.org/wiki/Stack

![image](https://cloud.githubusercontent.com/assets/1208815/7743841/a39c85ec-ff9e-11e4-9ce7-98ef5097c7b3.png)

When clicking the links, once gets to "empty" 101explorer pages.

This is very concerning because it means that students just cannot discover essential concepts.

**Comment by rlaemmel** [comment]
cc @hartenfels

**Comment by rlaemmel** [comment]
As I run into these issues and when they are important enough, then I am adding hard links to the markup -- this is what I just did to compensate for the bug. (Of course, this leads to somewhat polluted markup.)

**Comment by kevin-klein** [comment]
This is caused by the same problem that causes #65 The members modules not running just shuts down the explorer almost as a whole.
