### ISSUE TITLE
Lost content

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#79]
This page has gone missing, as I just noticed during the lecture.

Please restore from previously.

It looks like the UI does not provide any recover function anymore.

![image](https://cloud.githubusercontent.com/assets/1208815/7746198/cbdfa54a-ffb0-11e4-919f-d0acf004c3b9.png)

**Comment by kevin-klein** [comment]
Got your page back: http://101companies.org/wiki/Reverse_Polish_notation/
Searching for concept pages was sometimes broken due to a strange implementation of the search feature: b892a3fcc90472c488102c60470ed83e13c4596c
