### ISSUE TITLE
Strange backlinks

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#82]
Located here:

http://101companies.org/wiki/Script:Generic_functions

Seeing this:

![image](https://cloud.githubusercontent.com/assets/1208815/8723255/8ffc9a9a-2bcc-11e5-9607-14088268792d.png)

Too much "Lambdas in Koblenz".

**Comment by kevin-klein** [comment]
630a375ac5f36a906a5f19741e0591bc0f2db9be
