### ISSUE TITLE
repo folder cannot be selected

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#86]
I wanted to add the folder for a contribution; I can select the repo, but not the folder:

![image](https://cloud.githubusercontent.com/assets/1208815/9935985/1e84eb28-5d5a-11e5-83ca-106edbdfd333.png)

**Comment by kevin-klein** [comment]
This is fixed as well (6ad9003957c2f8702aa9ccc6f9f30554a69d59b3).
