### ISSUE TITLE
References not rendered

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#87]
The references are not rendered here:

http://101companies.org/wiki/Language:Scala

I don't see what's special about the page -- other pages correctly show references, e.g., this one:

http://101companies.org/wiki/Monad

I do seem to remember missing reference rendering on other pages too.

**Comment by kevin-klein** [comment]
ac632cff93b889f47578df41b8a16d02940ab7df
49a1dc9da02821195ac913bfd441d6db472c619f
8e4c48f63b6379ff98b608af09227e277fe1c2e7

Is fixed:
http://52.29.16.16/wiki/Language:Scala
The domain should become 101companies.org in the next few hours.
