### ISSUE TITLE
http://101companies.org/wiki/ needs to work for landing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#90]
The obvious question is what link to share when you want to link to the wiki.

Well, http://101companies.org/ seems to answer this question by linking the wiki button us to here:

http://101companies.org/wiki/@project

So this page could also be used for redirection from http://101companies.org/wiki/

But rather please redirect to here (please also use this for the button on http://101companies.org/):

http://101companies.org/wiki/@wiki

(Any such redirection should be in config files that are effectively backed up so that this works also after rebuilding the 101wiki machine/infrastructure).

**Comment by kevin-klein** [comment]
I will create a redirect in the nginx config which is already part of the deployment of 101rails (https://github.com/101companies/101rails/blob/master/config/deploy/templates/nginx_conf.erb).
