### ISSUE TITLE
Getting rid of the @s as in http://101companies.org/wiki/@project

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#91]
These URLs such as http://101companies.org/wiki/@project look awful.

The are also not rendered nice; see, for example, how @project is rendered as just @project on this page:

http://101companies.org/wiki/@wiki

So can we get rid of "@" and use 101 everywhere?

I seem to remember that we started with this crazy idiom when we had problems with (I think) Mediawiki because it had (I think) problems with names starting with digits. In fact, maybe this was a problem with some Javascript component. So some checking is needed to see whether this can actually safely done now, but please let's try.

**Comment by kevin-klein** [comment]
Changing the way of retrieving pages from the database is no issue but i would have to migrate all page contents which have links to "@" pages which will most likely result in some regex for this. I will have a try.

**Comment by kevin-klein** [comment]
Done
