### ISSUE TITLE
Page name with space cannot be used to create the page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#97]
Try to enter this:

       http://101companies.org/wiki/x y

It's rewritten to:

       http://101companies.org/wiki/x%20y

After confirming page creation, an error is displayed.

       There was a problem serving the requested page.

**Comment by kevin-klein** [comment]
The %20 escape by browsers is usual and correct, the issue is completly unrelated to spaces, there was a typo in some redirects for pages with names which contain anything but ascii characters.

**Comment by kevin-klein** [comment]
d0630371edc8097202ee3c68e028f2f5c9975866
